version: '3'
services:
  automacao_perf_vendedor:
    build: /home/ubuntu/kami-datalake/services/automacao_perf_vendedor
    ports:
      - "8501:8501"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    labels:
      - "traefik.enable=true"
      # Configuração para a aplicação principal na porta 8501
      - "traefik.http.routers.app-main.entrypoints=websecure"
      - "traefik.http.routers.app-main.tls.certresolver=myresolver"
      - "traefik.http.services.app-main.loadbalancer.server.port=8501"     

    restart: unless-stopped

networks:
  proxy:
    external: true