[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true

[client]
showErrorDetails = true

[global]
developmentMode = false